services:
  parthos-task-api:
    container_name: parthos-task-api
    build:
      context: .
    ports:
      - "3002:3002"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
    command: >
      sh -c "
      npm install &&
      npm run start:dev
      "
    networks:
      - parthos-network 

  db:
    image: postgres:14-alpine
    container_name: parthos-task-db
    environment:
    POSTGRES_USER: ${DB_USER}
    POSTGRES_PASSWORD: ${DB_PASS}
    POSTGRES_DB: ${DB_NAME}
    volumes:
      - parthos-data:/var/lib/postgresql/data
    networks:
      - parthos-network
    ports:
      - "${DB_PORT}:${DB_PORT}" 
volumes:
  parthos-task-data:

networks:
  parthos-network:
    external: true
